import React, { useState } from "react";

// Example data fetched from your files (cities and counties)
const cities = [
    {id: 1, title: 'ADANA'},
    {id: 2, title: 'ADIYAMAN'},
    {id: 3, title: 'AFYONKARAHİSAR'},
    {id: 4, title: 'AĞRI'},
    {id: 5, title: 'AMASYA'},
    {id: 6, title: 'ANKARA'},
    {id: 7, title: 'ANTALYA'},
    {id: 8, title: 'ARTVİN'},
    {id: 9, title: 'AYDIN'},
    {id: 10, title: 'BALIKESİR'},
    {id: 11, title: 'BİLECİK'},
    {id: 12, title: 'BİNGÖL'},
    {id: 13, title: 'BİTLİS'},
    {id: 14, title: 'BOLU'},
    {id: 15, title: 'BURDUR'},
    {id: 16, title: 'BURSA'},
    {id: 17, title: 'ÇANAKKALE'},
    {id: 18, title: 'ÇANKIRI'},
    {id: 19, title: 'ÇORUM'},
    {id: 20, title: 'DENİZLİ'},
    {id: 21, title: 'DİYARBAKIR'},
    {id: 22, title: 'EDİRNE'},
    {id: 23, title: 'ELAZIĞ'},
    {id: 24, title: 'ERZİNCAN'},
    {id: 25, title: 'ERZURUM'},
    {id: 26, title: 'ESKİŞEHİR'},
    {id: 27, title: 'GAZİANTEP'},
    {id: 28, title: 'GİRESUN'},
    {id: 29, title: 'GÜMÜŞHANE'},
    {id: 30, title: 'HAKKARİ'},
    {id: 31, title: 'HATAY'},
    {id: 32, title: 'ISPARTA'},
    {id: 33, title: 'MERSİN'},
    {id: 34, title: 'İSTANBUL'},
    {id: 35, title: 'İZMİR'},
    {id: 36, title: 'KARS'},
    {id: 37, title: 'KASTAMONU'},
    {id: 38, title: 'KAYSERİ'},
    {id: 39, title: 'KIRKLARELİ'},
    {id: 40, title: 'KIRŞEHİR'},
    {id: 41, title: 'KOCAELİ'},
    {id: 42, title: 'KONYA'},
    {id: 43, title: 'KÜTAHYA'},
    {id: 44, title: 'MALATYA'},
    {id: 45, title: 'MANİSA'},
    {id: 46, title: 'KAHRAMANMARAŞ'},
    {id: 47, title: 'MARDİN'},
    {id: 48, title: 'MUĞLA'},
    {id: 49, title: 'MUŞ'},
    {id: 50, title: 'NEVŞEHİR'},
    {id: 51, title: 'NİĞDE'},
    {id: 52, title: 'ORDU'},
    {id: 53, title: 'RİZE'},
    {id: 54, title: 'SAKARYA'},
    {id: 55, title: 'SAMSUN'},
    {id: 56, title: 'SİİRT'},
    {id: 57, title: 'SİNOP'},
    {id: 58, title: 'SİVAS'},
    {id: 59, title: 'TEKİRDAĞ'},
    {id: 60, title: 'TOKAT'},
    {id: 61, title: 'TRABZON'},
    {id: 62, title: 'TUNCELİ'},
    {id: 63, title: 'ŞANLIURFA'},
    {id: 64, title: 'UŞAK'},
    {id: 65, title: 'VAN'},
    {id: 66, title: 'YOZGAT'},
    {id: 67, title: 'ZONGULDAK'},
    {id: 68, title: 'AKSARAY'},
    {id: 69, title: 'BAYBURT'},
    {id: 70, title: 'KARAMAN'},
    {id: 71, title: 'KIRIKKALE'},
    {id: 72, title: 'BATMAN'},
    {id: 73, title: 'ŞIRNAK'},
    {id: 74, title: 'BARTIN'},
    {id: 75, title: 'ARDAHAN'},
    {id: 76, title: 'IĞDIR'},
    {id: 77, title: 'YALOVA'},
    {id: 78, title: 'KARABÜK'},
    {id: 79, title: 'KİLİS'},
    {id: 80, title: 'OSMANİYE'},
    {id: 81, title: 'DÜZCE'},
  // Add all other cities here
];

const counties = [
  {id: 1, city_id: 1, title: "ALADAĞ(KARSANTI)" },
  {id: 2, city_id: 1, title: "CEYHAN" },
  {id: 3, city_id: 1, title: 'ÇUKUROVA'},
  {id: 4, city_id: 1, title: 'FEKE'},
  {id: 5, city_id: 1, title: 'İMAMOĞLU'},
  {id: 6, city_id: 1, title: 'KARAİSALI'},
  {id: 7, city_id: 1, title: 'KARATAŞ'},
  {id: 8, city_id: 1, title: 'KOZAN'},
  {id: 9, city_id: 1, title: 'POZANTI'},
  {id: 10, city_id: 1, title: 'SAİMBEYLİ'},
  {id: 11, city_id: 1, title: 'SARIÇAM'},
  {id: 12, city_id: 1, title: 'SEYHAN'},
  {id: 13, city_id: 1, title: 'TUFANBEYLİ'},
  {id: 14, city_id: 1, title: 'YUMURTALIK'},
  {id: 15, city_id: 1, title: 'YÜREĞİR'},
  {id: 16, city_id: 2, title: 'ADIYAMAN'},
  {id: 17, city_id: 2, title: 'BESNİ'},
  {id: 18, city_id: 2, title: 'ÇELİKHAN'},
  {id: 19, city_id: 2, title: 'GERGER'},
  {id: 20, city_id: 2, title: 'GÖLBAŞI'},
  {id: 21, city_id: 2, title: 'KAHTA'},
  {id: 22, city_id: 2, title: 'SAMSAT'},
  {id: 23, city_id: 2, title: 'SİNCİK'},
  {id: 24, city_id: 2, title: 'TUT'},
  {id: 25, city_id: 3, title: 'AFYON'},
  {id: 26, city_id: 3, title: 'BAŞMAKÇI'},
  {id: 27, city_id: 3, title: 'BAYAT'},
  {id: 28, city_id: 3, title: 'BOLVADİN'},
  {id: 29, city_id: 3, title: 'ÇAY'},
  {id: 30, city_id: 3, title: 'ÇOBANLAR'},
  {id: 31, city_id: 3, title: 'DAZKIRI'},
  {id: 32, city_id: 3, title: 'DİNAR'},
  {id: 33, city_id: 3, title: 'EMİRDAĞ'},
  {id: 34, city_id: 3, title: 'EVCİLER'},
  {id: 35, city_id: 3, title: 'HOCALAR'},
  {id: 36, city_id: 3, title: 'İHSANİYE'},
  {id: 37, city_id: 3, title: 'İSCEHİSAR'},
  {id: 38, city_id: 3, title: 'KIZILÖREN'},
  {id: 39, city_id: 3, title: 'SANDIKLI'},
  {id: 40, city_id: 3, title: 'SİNCANLI'},
  {id: 41, city_id: 3, title: 'SULTANDAĞI'},
  {id: 42, city_id: 3, title: 'ŞUHUT'},
  {id: 43, city_id: 4, title: 'AĞRI'},
  {id: 44, city_id: 4, title: 'DİYADİN'},
  {id: 45, city_id: 4, title: 'DOĞUBAYAZIT'},
  {id: 46, city_id: 4, title: 'ELEŞKİRT'},
  {id: 47, city_id: 4, title: 'HAMUR'},
  {id: 48, city_id: 4, title: 'PATNOS'},
  {id: 49, city_id: 4, title: 'TAŞLIÇAY'},
  {id: 50, city_id: 4, title: 'TUTAK'},
  {id: 51, city_id: 5, title: 'AMASYA'},
  {id: 52, city_id: 5, title: 'GÖYNÜCEK'},
  {id: 53, city_id: 5, title: 'GÜMÜŞHACIKÖY'},
  {id: 54, city_id: 5, title: 'HAMAMÖZÜ'},
  {id: 55, city_id: 5, title: 'MERZİFON'},
  {id: 56, city_id: 5, title: 'SULUOVA'},
  {id: 57, city_id: 5, title: 'TAŞOVA'},
  {id: 58, city_id: 6, title: 'AKYURT'},
  {id: 59, city_id: 6, title: 'ALTINDAĞ'},
  {id: 60, city_id: 6, title: 'AYAŞ'},
  {id: 61, city_id: 6, title: 'BALA'},
  {id: 62, city_id: 6, title: 'BEYPAZARI'},
  {id: 63, city_id: 6, title: 'ÇAMLIDERE'},
  {id: 64, city_id: 6, title: 'ÇANKAYA'},
  {id: 65, city_id: 6, title: 'ÇUBUK'},
  {id: 66, city_id: 6, title: 'ELMADAĞ'},
  {id: 67, city_id: 6, title: 'ETİMESGUT'},
  {id: 68, city_id: 6, title: 'EVREN'},
  {id: 69, city_id: 6, title: 'GÖLBAŞI'},
  {id: 70, city_id: 6, title: 'GÜDÜL'},
  {id: 71, city_id: 6, title: 'HAYMANA'},
  {id: 72, city_id: 6, title: 'KALECİK'},
  {id: 73, city_id: 6, title: 'KAZAN'},
  {id: 74, city_id: 6, title: 'KEÇİÖREN'},
  {id: 75, city_id: 6, title: 'KIZILCAHAMAM'},
  {id: 76, city_id: 6, title: 'MAMAK'},
  {id: 77, city_id: 6, title: 'NALLIHAN'},
  {id: 78, city_id: 6, title: 'POLATLI'},
  {id: 79, city_id: 6, title: 'PURSAKLAR'},
  {id: 80, city_id: 6, title: 'SİNCAN'},
  {id: 81, city_id: 6, title: 'ŞEREFLİKOÇHİSAR'},
  {id: 82, city_id: 6, title: 'YENİMAHALLE'},
  {id: 83, city_id: 7, title: 'AKSEKİ'},
  {id: 84, city_id: 7, title: 'AKSU'},
  {id: 85, city_id: 7, title: 'ALANYA'},
  {id: 86, city_id: 7, title: 'DEMRE'},
  {id: 87, city_id: 7, title: 'DÖŞEMEALTI'},
  {id: 88, city_id: 7, title: 'ELMALI'},
  {id: 89, city_id: 7, title: 'FİNİKE'},
  {id: 90, city_id: 7, title: 'GAZİPAŞA'},
  {id: 91, city_id: 7, title: 'GÜNDOĞMUŞ'},
  {id: 92, city_id: 7, title: 'İBRADI'},
  {id: 93, city_id: 7, title: 'KAŞ'},
  {id: 94, city_id: 7, title: 'KEMER'},
  {id: 95, city_id: 7, title: 'KEPEZ'},
  {id: 96, city_id: 7, title: 'KONYAALTI'},
  {id: 97, city_id: 7, title: 'KORKUTELİ'},
  {id: 98, city_id: 7, title: 'KUMLUCA'},
  {id: 99, city_id: 7, title: 'MANAVGAT'},
  {id: 100, city_id: 7, title: 'MURATPAŞA'},
  {id: 101, city_id: 7, title: 'SERİK'},
  {id: 102, city_id: 8, title: 'ARDANUÇ'},
  {id: 103, city_id: 8, title: 'ARHAVİ'},
  {id: 104, city_id: 8, title: 'ARTVİN'},
  {id: 105, city_id: 8, title: 'BORÇKA'},
  {id: 106, city_id: 8, title: 'HOPA'},
  {id: 107, city_id: 8, title: 'MURGUL'},
  {id: 108, city_id: 8, title: 'ŞAVŞAT'},
  {id: 109, city_id: 8, title: 'YUSUFELİ'},
  {id: 110, city_id: 9, title: 'AYDIN'},
  {id: 111, city_id: 9, title: 'BOZDOĞAN'},
  {id: 112, city_id: 9, title: 'BUHARKENT'},
  {id: 113, city_id: 9, title: 'ÇİNE'},
  {id: 114, city_id: 9, title: 'DİDİM'},
  {id: 115, city_id: 9, title: 'GERMENCİK'},
  {id: 116, city_id: 9, title: 'İNCİRLİOVA'},
  {id: 117, city_id: 9, title: 'KARACASU'},
  {id: 118, city_id: 9, title: 'KARPUZLU'},
  {id: 119, city_id: 9, title: 'KOÇARLI'},
  {id: 120, city_id: 9, title: 'KÖŞK'},
  {id: 121, city_id: 9, title: 'KUŞADASI'},
  {id: 122, city_id: 9, title: 'KUYUCAK'},
  {id: 123, city_id: 9, title: 'NAZİLLİ'},
  {id: 124, city_id: 9, title: 'SÖKE'},
  {id: 125, city_id: 9, title: 'SULTANHİSAR'},
  {id: 126, city_id: 9, title: 'YENİPAZAR'},
  {id: 127, city_id: 10, title: 'AYVALIK'},
  {id: 128, city_id: 10, title: 'BALIKESİR'},
  {id: 129, city_id: 10, title: 'BALYA'},
  {id: 130, city_id: 10, title: 'BANDIRMA'},
  {id: 131, city_id: 10, title: 'BİGADİÇ'},
  {id: 132, city_id: 10, title: 'BURHANİYE'},
  {id: 133, city_id: 10, title: 'DURSUNBEY'},
  {id: 134, city_id: 10, title: 'EDREMİT'},
  {id: 135, city_id: 10, title: 'ERDEK'},
  {id: 136, city_id: 10, title: 'GÖMEÇ'},
  {id: 137, city_id: 10, title: 'GÖNEN'},
  {id: 138, city_id: 10, title: 'HAVRAN'},
  {id: 139, city_id: 10, title: 'İVRİNDİ'},
  {id: 140, city_id: 10, title: 'KEPSUT'},
  {id: 141, city_id: 10, title: 'MANYAS'},
  {id: 142, city_id: 10, title: 'MARMARA'},
  {id: 143, city_id: 10, title: 'SAVAŞTEPE'},
  {id: 144, city_id: 10, title: 'SINDIRGI'},
  {id: 145, city_id: 10, title: 'SUSURLUK'},
  {id: 146, city_id: 11, title: 'BİLECİK'},
  {id: 147, city_id: 11, title: 'BOZÜYÜK'},
  {id: 148, city_id: 11, title: 'GÖLPAZARI'},
  {id: 149, city_id: 11, title: 'İNHİSAR'},
  {id: 150, city_id: 11, title: 'OSMANELİ'},
  {id: 151, city_id: 11, title: 'PAZARYERİ'},
  {id: 152, city_id: 11, title: 'SÖĞÜT'},
  {id: 153, city_id: 11, title: 'YENİPAZAR'},
  {id: 154, city_id: 12, title: 'ADAKLI'},
  {id: 155, city_id: 12, title: 'BİNGÖL'},
  {id: 156, city_id: 12, title: 'GENÇ'},
  {id: 157, city_id: 12, title: 'KARLIOVA'},
  {id: 158, city_id: 12, title: 'KİĞI'},
  {id: 159, city_id: 12, title: 'SOLHAN'},
  {id: 160, city_id: 12, title: 'YAYLADERE'},
  {id: 161, city_id: 12, title: 'YEDİSU'},
  {id: 162, city_id: 13, title: 'ADİLCEVAZ'},
  {id: 163, city_id: 13, title: 'AHLAT'},
  {id: 164, city_id: 13, title: 'BİTLİS'},
  {id: 165, city_id: 13, title: 'GÜROYMAK'},
  {id: 166, city_id: 13, title: 'HİZAN'},
  {id: 167, city_id: 13, title: 'MUTKİ'},
  {id: 168, city_id: 13, title: 'TATVAN'},
  {id: 169, city_id: 14, title: 'BOLU'},
  {id: 170, city_id: 14, title: 'DÖRTDİVAN'},
  {id: 171, city_id: 14, title: 'GEREDE'},
  {id: 172, city_id: 14, title: 'GÖYNÜK'},
  {id: 173, city_id: 14, title: 'KIBRISCIK'},
  {id: 174, city_id: 14, title: 'MENGEN'},
  {id: 175, city_id: 14, title: 'MUDURNU'},
  {id: 176, city_id: 14, title: 'SEBEN'},
  {id: 177, city_id: 14, title: 'YENİÇAĞA'},
  {id: 178, city_id: 15, title: 'AĞLASUN'},
  {id: 179, city_id: 15, title: 'ALTINYAYLA'},
  {id: 180, city_id: 15, title: 'BUCAK'},
  {id: 181, city_id: 15, title: 'BURDUR'},
  {id: 182, city_id: 15, title: 'ÇAVDIR'},
  {id: 183, city_id: 15, title: 'ÇELTİKÇİ'},
  {id: 184, city_id: 15, title: 'GÖLHİSAR'},
  {id: 185, city_id: 15, title: 'KARAMANLI'},
  {id: 186, city_id: 15, title: 'KEMER'},
  {id: 187, city_id: 15, title: 'TEFENNİ'},
  {id: 188, city_id: 15, title: 'YEŞİLOVA'},
  {id: 189, city_id: 16, title: 'BÜYÜKORHAN'},
  {id: 190, city_id: 16, title: 'GEMLİK'},
  {id: 191, city_id: 16, title: 'GÜRSU'},
  {id: 192, city_id: 16, title: 'HARMANCIK'},
  {id: 193, city_id: 16, title: 'İNEGÖL'},
  {id: 194, city_id: 16, title: 'İZNİK'},
  {id: 195, city_id: 16, title: 'KARACABEY'},
  {id: 196, city_id: 16, title: 'KELES'},
  {id: 197, city_id: 16, title: 'KESTEL'},
  {id: 198, city_id: 16, title: 'MUDANYA'},
  {id: 199, city_id: 16, title: 'MUSTAFAKEMALPAŞA'},
  {id: 200, city_id: 16, title: 'NİLÜFER'},
  {id: 201, city_id: 16, title: 'ORHANELİ'},
  {id: 202, city_id: 16, title: 'ORHANGAZİ'},
  {id: 203, city_id: 16, title: 'OSMANGAZİ'},
  {id: 204, city_id: 16, title: 'YENİŞEHİR'},
  {id: 205, city_id: 16, title: 'YILDIRIM'},
  {id: 206, city_id: 17, title: 'AYVACIK'},
  {id: 207, city_id: 17, title: 'BAYRAMİÇ'},
  {id: 208, city_id: 17, title: 'BİGA'},
  {id: 209, city_id: 17, title: 'BOZCAADA'},
  {id: 210, city_id: 17, title: 'ÇAN'},
  {id: 211, city_id: 17, title: 'ÇANAKKALE'},
  {id: 212, city_id: 17, title: 'ECEABAT'},
  {id: 213, city_id: 17, title: 'EZİNE'},
  {id: 214, city_id: 17, title: 'GELİBOLU'},
  {id: 215, city_id: 17, title: 'GÖKÇEADA'},
  {id: 216, city_id: 17, title: 'LAPSEKİ'},
  {id: 217, city_id: 17, title: 'YENİCE'},
  {id: 218, city_id: 18, title: 'ATKARACALAR'},
  {id: 219, city_id: 18, title: 'BAYRAMÖREN'},
  {id: 220, city_id: 18, title: 'ÇANKIRI'},
  {id: 221, city_id: 18, title: 'ÇERKEŞ'},
  {id: 222, city_id: 18, title: 'ELDİVAN'},
  {id: 223, city_id: 18, title: 'ILGAZ'},
  {id: 224, city_id: 18, title: 'KIZILIRMAK'},
  {id: 225, city_id: 18, title: 'KORGUN'},
  {id: 226, city_id: 18, title: 'KURŞUNLU'},
  {id: 227, city_id: 18, title: 'ORTA'},
  {id: 228, city_id: 18, title: 'ŞABANÖZÜ'},
  {id: 229, city_id: 18, title: 'YAPRAKLI'},
  {id: 230, city_id: 19, title: 'ALACA'},
  {id: 231, city_id: 19, title: 'BAYAT'},
  {id: 232, city_id: 19, title: 'BOĞAZKALE'},
  {id: 233, city_id: 19, title: 'ÇORUM'},
  {id: 234, city_id: 19, title: 'DODURGA'},
  {id: 235, city_id: 19, title: 'İSKİLİP'},
  {id: 236, city_id: 19, title: 'KARGI'},
  {id: 237, city_id: 19, title: 'LAÇİN'},
  {id: 238, city_id: 19, title: 'MECİTÖZÜ'},
  {id: 239, city_id: 19, title: 'OĞUZLAR'},
  {id: 240, city_id: 19, title: 'ORTAKÖY'},
  {id: 241, city_id: 19, title: 'OSMANCIK'},
  {id: 242, city_id: 19, title: 'SUNGURLU'},
  {id: 243, city_id: 19, title: 'UĞURLUDAĞ'},
  {id: 244, city_id: 20, title: 'ACIPAYAM'},
  {id: 245, city_id: 20, title: 'AKKÖY'},
  {id: 246, city_id: 20, title: 'BABADAĞ'},
  {id: 247, city_id: 20, title: 'BAKLAN'},
  {id: 248, city_id: 20, title: 'BEKİLLİ'},
  {id: 249, city_id: 20, title: 'BEYAĞAÇ'},
  {id: 250, city_id: 20, title: 'BOZKURT'},
  {id: 251, city_id: 20, title: 'BULDAN'},
  {id: 252, city_id: 20, title: 'ÇAL'},
  {id: 253, city_id: 20, title: 'ÇAMELİ'},
  {id: 254, city_id: 20, title: 'ÇARDAK'},
  {id: 255, city_id: 20, title: 'ÇİVRİL'},
  {id: 256, city_id: 20, title: 'DENİZLİ'},
  {id: 257, city_id: 20, title: 'GÜNEY'},
  {id: 258, city_id: 20, title: 'HONAZ'},
  {id: 259, city_id: 20, title: 'KALE'},
  {id: 260, city_id: 20, title: 'SARAYKÖY'},
  {id: 261, city_id: 20, title: 'SERİNHİSAR'},
  {id: 262, city_id: 20, title: 'TAVAS'},
  {id: 263, city_id: 21, title: 'BAĞLAR'},
  {id: 264, city_id: 21, title: 'BİSMİL'},
  {id: 265, city_id: 21, title: 'ÇERMİK'},
  {id: 266, city_id: 21, title: 'ÇINAR'},
  {id: 267, city_id: 21, title: 'ÇÜNGÜŞ'},
  {id: 268, city_id: 21, title: 'DİCLE'},
  {id: 269, city_id: 21, title: 'EĞİL'},
  {id: 270, city_id: 21, title: 'ERGANİ'},
  {id: 271, city_id: 21, title: 'HANİ'},
  {id: 272, city_id: 21, title: 'HAZRO'},
  {id: 273, city_id: 21, title: 'KAYAPINAR'},
  {id: 274, city_id: 21, title: 'KOCAKÖY'},
  {id: 275, city_id: 21, title: 'KULP'},
  {id: 276, city_id: 21, title: 'LİCE'},
  {id: 277, city_id: 21, title: 'SİLVAN'},
  {id: 278, city_id: 21, title: 'SUR'},
  {id: 279, city_id: 21, title: 'YENİŞEHİR'},
  {id: 280, city_id: 22, title: 'EDİRNE'},
  {id: 281, city_id: 22, title: 'ENEZ'},
  {id: 282, city_id: 22, title: 'HAVSA'},
  {id: 283, city_id: 22, title: 'İPSALA'},
  {id: 284, city_id: 22, title: 'KEŞAN'},
  {id: 285, city_id: 22, title: 'LALAPAŞA'},
  {id: 286, city_id: 22, title: 'MERİÇ'},
  {id: 287, city_id: 22, title: 'SÜLOĞLU'},
  {id: 288, city_id: 22, title: 'UZUNKÖPRÜ'},
  {id: 289, city_id: 23, title: 'AĞIN'},
  {id: 290, city_id: 23, title: 'ALACAKAYA'},
  {id: 291, city_id: 23, title: 'ARICAK'},
  {id: 292, city_id: 23, title: 'BASKİL'},
  {id: 293, city_id: 23, title: 'ELAZIĞ'},
  {id: 294, city_id: 23, title: 'KARAKOÇAN'},
  {id: 295, city_id: 23, title: 'KEBAN'},
  {id: 296, city_id: 23, title: 'KOVANCILAR'},
  {id: 297, city_id: 23, title: 'MADEN'},
  {id: 298, city_id: 23, title: 'PALU'},
  {id: 299, city_id: 23, title: 'SİVRİCE'},
  {id: 300, city_id: 24, title: 'ÇAYIRLI'},
  {id: 301, city_id: 24, title: 'ERZİNCAN'},
  {id: 302, city_id: 24, title: 'ILIÇ'},
  {id: 303, city_id: 24, title: 'KEMAH'},
  {id: 304, city_id: 24, title: 'KEMALİYE'},
  {id: 305, city_id: 24, title: 'OTLUKBELİ'},
  {id: 306, city_id: 24, title: 'REFAHİYE'},
  {id: 307, city_id: 24, title: 'TERCAN'},
  {id: 308, city_id: 24, title: 'ÜZÜMLÜ'},
  {id: 309, city_id: 25, title: 'AŞKALE'},
  {id: 310, city_id: 25, title: 'AZİZİYE'},
  {id: 311, city_id: 25, title: 'ÇAT'},
  {id: 312, city_id: 25, title: 'HINIS'},
  {id: 313, city_id: 25, title: 'HORASAN'},
  {id: 314, city_id: 25, title: 'İSPİR'},
  {id: 315, city_id: 25, title: 'KARAÇOBAN'},
  {id: 316, city_id: 25, title: 'KARAYAZI'},
  {id: 317, city_id: 25, title: 'KÖPRÜKÖY'},
  {id: 318, city_id: 25, title: 'NARMAN'},
  {id: 319, city_id: 25, title: 'OLTU'},
  {id: 320, city_id: 25, title: 'OLUR'},
  {id: 321, city_id: 25, title: 'PALANDÖKEN'},
  {id: 322, city_id: 25, title: 'PASİNLER'},
  {id: 323, city_id: 25, title: 'PAZARYOLU'},
  {id: 324, city_id: 25, title: 'ŞENKAYA'},
  {id: 325, city_id: 25, title: 'TEKMAN'},
  {id: 326, city_id: 25, title: 'TORTUM'},
  {id: 327, city_id: 25, title: 'UZUNDERE'},
  {id: 328, city_id: 25, title: 'YAKUTİYE'},
  {id: 329, city_id: 26, title: 'ALPU'},
  {id: 330, city_id: 26, title: 'BEYLİKOVA'},
  {id: 331, city_id: 26, title: 'ÇİFTELER'},
  {id: 332, city_id: 26, title: 'GÜNYÜZÜ'},
  {id: 333, city_id: 26, title: 'HAN'},
  {id: 334, city_id: 26, title: 'İNÖNÜ'},
  {id: 335, city_id: 26, title: 'MAHMUDİYE'},
  {id: 336, city_id: 26, title: 'MİHALGAZİ'},
  {id: 337, city_id: 26, title: 'MİHALIÇÇIK'},
  {id: 338, city_id: 26, title: 'ODUNPAZARI'},
  {id: 339, city_id: 26, title: 'SARICAKAYA'},
  {id: 340, city_id: 26, title: 'SEYİTGAZİ'},
  {id: 341, city_id: 26, title: 'SİVRİHİSAR'},
  {id: 342, city_id: 26, title: 'TEPEBAŞI'},
  {id: 343, city_id: 27, title: 'ARABAN'},
  {id: 344, city_id: 27, title: 'İSLAHİYE'},
  {id: 345, city_id: 27, title: 'KARKAMIŞ'},
  {id: 346, city_id: 27, title: 'NİZİP'},
  {id: 347, city_id: 27, title: 'NURDAĞI'},
  {id: 348, city_id: 27, title: 'OĞUZELİ'},
  {id: 349, city_id: 27, title: 'ŞAHİNBEY'},
  {id: 350, city_id: 27, title: 'ŞEHİTKAMİL'},
  {id: 351, city_id: 27, title: 'YAVUZELİ'},
  {id: 352, city_id: 28, title: 'ALUCRA'},
  {id: 353, city_id: 28, title: 'BULANCAK'},
  {id: 354, city_id: 28, title: 'ÇAMOLUK'},
  {id: 355, city_id: 28, title: 'ÇANAKÇI'},
  {id: 356, city_id: 28, title: 'DERELİ'},
  {id: 357, city_id: 28, title: 'DOĞANKENT'},
  {id: 358, city_id: 28, title: 'ESPİYE'},
  {id: 359, city_id: 28, title: 'EYNESİL'},
  {id: 360, city_id: 28, title: 'GİRESUN'},
  {id: 361, city_id: 28, title: 'GÖRELE'},
  {id: 362, city_id: 28, title: 'GÜCE'},
  {id: 363, city_id: 28, title: 'KEŞAP'},
  {id: 364, city_id: 28, title: 'PİRAZİZ'},
  {id: 365, city_id: 28, title: 'ŞEBİNKARAHİSAR'},
  {id: 366, city_id: 28, title: 'TİREBOLU'},
  {id: 367, city_id: 28, title: 'YAĞLIDERE'},
  {id: 368, city_id: 29, title: 'GÜMÜŞHANE'},
  {id: 369, city_id: 29, title: 'KELKİT'},
  {id: 370, city_id: 29, title: 'KÖSE'},
  {id: 371, city_id: 29, title: 'KÜRTÜN'},
  {id: 372, city_id: 29, title: 'ŞİRAN'},
  {id: 373, city_id: 29, title: 'TORUL'},
  {id: 374, city_id: 30, title: 'ÇUKURCA'},
  {id: 375, city_id: 30, title: 'HAKKARİ'},
  {id: 376, city_id: 30, title: 'ŞEMDİNLİ'},
  {id: 377, city_id: 30, title: 'YÜKSEKOVA'},
  {id: 378, city_id: 31, title: 'ALTINÖZÜ'},
  {id: 379, city_id: 31, title: 'ANTAKYA'},
  {id: 380, city_id: 31, title: 'BELEN'},
  {id: 381, city_id: 31, title: 'DÖRTYOL'},
  {id: 382, city_id: 31, title: 'ERZİN'},
  {id: 383, city_id: 31, title: 'HASSA'},
  {id: 384, city_id: 31, title: 'İSKENDERUN'},
  {id: 385, city_id: 31, title: 'KIRIKHAN'},
  {id: 386, city_id: 31, title: 'KUMLU'},
  {id: 387, city_id: 31, title: 'REYHANLI'},
  {id: 388, city_id: 31, title: 'SAMANDAĞ'},
  {id: 389, city_id: 31, title: 'YAYLADAĞI'},
  {id: 390, city_id: 32, title: 'AKSU'},
  {id: 391, city_id: 32, title: 'ATABEY'},
  {id: 392, city_id: 32, title: 'EĞİRDİR'},
  {id: 393, city_id: 32, title: 'GELENDOST'},
  {id: 394, city_id: 32, title: 'GÖNEN'},
  {id: 395, city_id: 32, title: 'ISPARTA'},
  {id: 396, city_id: 32, title: 'KEÇİBORLU'},
  {id: 397, city_id: 32, title: 'SENİRKENT'},
  {id: 398, city_id: 32, title: 'SÜTÇÜLER'},
  {id: 399, city_id: 32, title: 'ŞARKİKARAAĞAÇ'},
  {id: 400, city_id: 32, title: 'ULUBORLU'},
  {id: 401, city_id: 32, title: 'YALVAÇ'},
  {id: 402, city_id: 32, title: 'YENİŞARBADEMLİ'},
  {id: 403, city_id: 33, title: 'AKDENİZ'},
  {id: 404, city_id: 33, title: 'ANAMUR'},
  {id: 405, city_id: 33, title: 'AYDINCIK'},
  {id: 406, city_id: 33, title: 'BOZYAZI'},
  {id: 407, city_id: 33, title: 'ÇAMLIYAYLA'},
  {id: 408, city_id: 33, title: 'ERDEMLİ'},
  {id: 409, city_id: 33, title: 'GÜLNAR' },
  {id: 410, city_id: 33, title: 'MEZİTLİ'},
  {id: 411, city_id: 33, title: 'MUT'},
  {id: 412, city_id: 33, title: 'SİLİFKE'},
  {id: 413, city_id: 33, title: 'TARSUS'},
  {id: 414, city_id: 33, title: 'TOROSLAR'},
  {id: 415, city_id: 33, title: 'YENİŞEHİR'},
  {id: 416, city_id: 34, title: 'ADALAR'},
  {id: 417, city_id: 34, title: 'ARNAVUTKÖY'},
  {id: 418, city_id: 34, title: 'ATAŞEHİR'},
  {id: 419, city_id: 34, title: 'AVCILAR'},
  {id: 420, city_id: 34, title: 'BAĞCILAR'},
  {id: 421, city_id: 34, title: 'BAHÇELİEVLER'},
  {id: 422, city_id: 34, title: 'BAKIRKÖY'},
  {id: 423, city_id: 34, title: 'BAŞAKŞEHİR'},
  {id: 424, city_id: 34, title: 'BAYRAMPAŞA'},
  {id: 425, city_id: 34, title: 'BEŞİKTAŞ'},
  {id: 426, city_id: 34, title: 'BEYKOZ'},
  {id: 427, city_id: 34, title: 'BEYLİKDÜZÜ'},
  {id: 428, city_id: 34, title: 'BEYOĞLU'},
  {id: 429, city_id: 34, title: 'BÜYÜKÇEKMECE'},
  {id: 430, city_id: 34, title: 'ÇATALCA'},
  {id: 431, city_id: 34, title: 'ÇEKMEKÖY'},
  {id: 432, city_id: 34, title: 'ESENLER'},
  {id: 433, city_id: 34, title: 'ESENYURT'},
  {id: 434, city_id: 34, title: 'EYÜP'},
  {id: 435, city_id: 34, title: 'FATİH'},
  {id: 436, city_id: 34, title: 'GAZİOSMANPAŞA'},
  {id: 437, city_id: 34, title: 'GÜNGÖREN'},
  {id: 438, city_id: 34, title: 'KADIKÖY'},
  {id: 439, city_id: 34, title: 'KAĞITHANE'},
  {id: 440, city_id: 34, title: 'KARTAL'},
  {id: 441, city_id: 34, title: 'KÜÇÜKÇEKMECE'},
  {id: 442, city_id: 34, title: 'MALTEPE'},
  {id: 443, city_id: 34, title: 'PENDİK'},
  {id: 444, city_id: 34, title: 'SANCAKTEPE'},
  {id: 445, city_id: 34, title: 'SARIYER'},
  {id: 446, city_id: 34, title: 'SİLİVRİ'},
  {id: 447, city_id: 34, title: 'SULTANBEYLİ'},
  {id: 448, city_id: 34, title: 'SULTANGAZİ'},
  {id: 449, city_id: 34, title: 'ŞİLE'},
  {id: 450, city_id: 34, title: 'ŞİŞLİ'},
  {id: 451, city_id: 34, title: 'TUZLA'},
  {id: 452, city_id: 34, title: 'ÜMRANİYE'},
  {id: 453, city_id: 34, title: 'ÜSKÜDAR'},
  {id: 454, city_id: 34, title: 'ZEYTİNBURNU'},
  {id: 455, city_id: 35, title: 'ALİAĞA'},
  {id: 456, city_id: 35, title: 'BALÇOVA'},
  {id: 457, city_id: 35, title: 'BAYINDIR'},
  {id: 458, city_id: 35, title: 'BAYRAKLI'},
  {id: 459, city_id: 35, title: 'BERGAMA'},
  {id: 460, city_id: 35, title: 'BEYDAĞ'},
  {id: 461, city_id: 35, title: 'BORNOVA'},
  {id: 462, city_id: 35, title: 'BUCA'},
  {id: 463, city_id: 35, title: 'ÇEŞME'},
  {id: 464, city_id: 35, title: 'ÇİĞLİ'},
  {id: 465, city_id: 35, title: 'DİKİLİ'},
  {id: 466, city_id: 35, title: 'FOÇA'},
  {id: 467, city_id: 35, title: 'GAZİEMİR'},
  {id: 468, city_id: 35, title: 'GÜZELBAHÇE'},
  {id: 469, city_id: 35, title: 'KARABAĞLAR'},
  {id: 470, city_id: 35, title: 'KARABURUN'},
  {id: 471, city_id: 35, title: 'KARŞIYAKA'},
  {id: 472, city_id: 35, title: 'KEMALPAŞA'},
  {id: 473, city_id: 35, title: 'KINIK'},
  {id: 474, city_id: 35, title: 'KİRAZ'},
  {id: 475, city_id: 35, title: 'KONAK'},
  {id: 476, city_id: 35, title: 'MENDERES'},
  {id: 477, city_id: 35, title: 'MENEMEN'},
  {id: 478, city_id: 35, title: 'NARLIDERE'},
  {id: 479, city_id: 35, title: 'ÖDEMİŞ'},
  {id: 480, city_id: 35, title: 'SEFERİHİSAR'},
  {id: 481, city_id: 35, title: 'SELÇUK'},
  {id: 482, city_id: 35, title: 'TİRE'},
  {id: 483, city_id: 35, title: 'TORBALI'},
  {id: 484, city_id: 35, title: 'URLA'},
  {id: 485, city_id: 36, title: 'AKYAKA'},
  {id: 486, city_id: 36, title: 'ARPAÇAY'},
  {id: 487, city_id: 36, title: 'DİGOR'},
  {id: 488, city_id: 36, title: 'KAĞIZMAN'},
  {id: 489, city_id: 36, title: 'KARS'},
  {id: 490, city_id: 36, title: 'SARIKAMIŞ'},
  {id: 491, city_id: 36, title: 'SELİM'},
  {id: 492, city_id: 36, title: 'SUSUZ'},
  {id: 493, city_id: 37, title: 'ABANA'},
  {id: 494, city_id: 37, title: 'AĞLI'},
  {id: 495, city_id: 37, title: 'ARAÇ'},
  {id: 496, city_id: 37, title: 'AZDAVAY'},
  {id: 497, city_id: 37, title: 'BOZKURT'},
  {id: 498, city_id: 37, title: 'CİDE'},
  {id: 499, city_id: 37, title: 'ÇATALZEYTİN'},
  {id: 500, city_id: 37, title: 'DADAY'},
  {id: 501, city_id: 37, title: 'DEVREKANİ'},
  {id: 502, city_id: 37, title: 'DOĞANYURT'},
  {id: 503, city_id: 37, title: 'HANÖNÜ'},
  {id: 504, city_id: 37, title: 'İHSANGAZİ'},
  {id: 505, city_id: 37, title: 'İNEBOLU'},
  {id: 506, city_id: 37, title: 'KASTAMONU'},
  {id: 507, city_id: 37, title: 'KÜRE'},
  {id: 508, city_id: 37, title: 'PINARBAŞI'},
  {id: 509, city_id: 37, title: 'SEYDİLER'},
  {id: 510, city_id: 37, title: 'ŞENPAZAR'},
  {id: 511, city_id: 37, title: 'TAŞKÖPRÜ'},
  {id: 512, city_id: 37, title: 'TOSYA'},
  {id: 513, city_id: 38, title: 'AKKIŞLA'},
  {id: 514, city_id: 38, title: 'BÜNYAN'},
  {id: 515, city_id: 38, title: 'DEVELİ'},
  {id: 516, city_id: 38, title: 'FELAHİYE'},
  {id: 517, city_id: 38, title: 'HACILAR'},
  {id: 518, city_id: 38, title: 'İNCESU'},
  {id: 519, city_id: 38, title: 'KOCASİNAN'},
  {id: 520, city_id: 38, title: 'MELİKGAZİ'},
  {id: 521, city_id: 38, title: 'ÖZVATAN'},
  {id: 522, city_id: 38, title: 'PINARBAŞI'},
  {id: 523, city_id: 38, title: 'SARIOĞLAN'},
  {id: 524, city_id: 38, title: 'SARIZ'},
  {id: 525, city_id: 38, title: 'TALAS'},
  {id: 526, city_id: 38, title: 'TOMARZA'},
  {id: 527, city_id: 38, title: 'YAHYALI'},
  {id: 528, city_id: 38, title: 'YEŞİLHİSAR'},
  {id: 529, city_id: 39, title: 'BABAESKİ'},
  {id: 530, city_id: 39, title: 'DEMİRKÖY'},
  {id: 531, city_id: 39, title: 'KIRKLARELİ'},
  {id: 532, city_id: 39, title: 'KOFÇAZ'},
  {id: 533, city_id: 39, title: 'LÜLEBURGAZ'},
  {id: 534, city_id: 39, title: 'PEHLİVANKÖY'},
  {id: 535, city_id: 39, title: 'PINARHİSAR'},
  {id: 536, city_id: 39, title: 'VİZE'},
  {id: 537, city_id: 40, title: 'AKÇAKENT'},
  {id: 538, city_id: 40, title: 'AKPINAR'},
  {id: 539, city_id: 40, title: 'BOZTEPE'},
  {id: 540, city_id: 40, title: 'ÇİÇEKDAĞI'},
  {id: 541, city_id: 40, title: 'KAMAN'},
  {id: 542, city_id: 40, title: 'KIRŞEHİR'},
  {id: 543, city_id: 40, title: 'MUCUR'},
  {id: 544, city_id: 41, title: 'BAŞİSKELE'},
  {id: 545, city_id: 41, title: 'ÇAYIROVA'},
  {id: 546, city_id: 41, title: 'DARICA'},
  {id: 547, city_id: 41, title: 'DERİNCE'},
  {id: 548, city_id: 41, title: 'DİLOVASI'},
  {id: 549, city_id: 41, title: 'GEBZE'},
  {id: 550, city_id: 41, title: 'GÖLCÜK'},
  {id: 551, city_id: 41, title: 'İZMİT'},
  {id: 552, city_id: 41, title: 'KANDIRA'},
  {id: 553, city_id: 41, title: 'KARAMÜRSEL'},
  {id: 554, city_id: 41, title: 'KARTEPE'},
  {id: 555, city_id: 41, title: 'KÖRFEZ'},
  {id: 556, city_id: 42, title: 'AHIRLI'},
  {id: 557, city_id: 42, title: 'AKÖREN'},
  {id: 558, city_id: 42, title: 'AKŞEHİR'},
  {id: 559, city_id: 42, title: 'ALTINEKİN'},
  {id: 560, city_id: 42, title: 'BEYŞEHİR'},
  {id: 561, city_id: 42, title: 'BOZKIR'},
  {id: 562, city_id: 42, title: 'CİHANBEYLİ'},
  {id: 563, city_id: 42, title: 'ÇELTİK'},
  {id: 564, city_id: 42, title: 'ÇUMRA'},
  {id: 565, city_id: 42, title: 'DERBENT'},
  {id: 566, city_id: 42, title: 'DEREBUCAK'},
  {id: 567, city_id: 42, title: 'DOĞANHİSAR'},
  {id: 568, city_id: 42, title: 'EMİRGAZİ'},
  {id: 569, city_id: 42, title: 'EREĞLİ'},
  {id: 570, city_id: 42, title: 'GÜNEYSINIR'},
  {id: 571, city_id: 42, title: 'HADİM'},
  {id: 572, city_id: 42, title: 'HALKAPINAR'},
  {id: 573, city_id: 42, title: 'HÜYÜK'},
  {id: 574, city_id: 42, title: 'ILGIN'},
  {id: 575, city_id: 42, title: 'KADINHANI'},
  {id: 576, city_id: 42, title: 'KARAPINAR'},
  {id: 577, city_id: 42, title: 'KARATAY'},
  {id: 578, city_id: 42, title: 'KULU'},
  {id: 579, city_id: 42, title: 'MERAM'},
  {id: 580, city_id: 42, title: 'SARAYÖNÜ'},
  {id: 581, city_id: 42, title: 'SELÇUKLU'},
  {id: 582, city_id: 42, title: 'SEYDİŞEHİR'},
  {id: 583, city_id: 42, title: 'TAŞKENT'},
  {id: 584, city_id: 42, title: 'TUZLUKÇU'},
  {id: 585, city_id: 42, title: 'YALIHÜYÜK'},
  {id: 586, city_id: 42, title: 'YUNAK'},
  {id: 587, city_id: 43, title: 'ALTINTAŞ'},
  {id: 588, city_id: 43, title: 'ASLANAPA'},
  {id: 589, city_id: 43, title: 'ÇAVDARHİSAR'},
  {id: 590, city_id: 43, title: 'DOMANİÇ'},
  {id: 591, city_id: 43, title: 'DUMLUPINAR'},
  {id: 592, city_id: 43, title: 'EMET'},
  {id: 593, city_id: 43, title: 'GEDİZ'},
  {id: 594, city_id: 43, title: 'HİSARCIK'},
  {id: 595, city_id: 43, title: 'KÜTAHYA'},
  {id: 596, city_id: 43, title: 'PAZARLAR'},
  {id: 597, city_id: 43, title: 'SİMAV'},
  {id: 598, city_id: 43, title: 'ŞAPHANE'},
  {id: 599, city_id: 43, title: 'TAVŞANLI'},
  {id: 600, city_id: 44, title: 'AKÇADAĞ'},
  {id: 601, city_id: 44, title: 'ARAPKİR'},
  {id: 602, city_id: 44, title: 'ARGUVAN'},
  {id: 603, city_id: 44, title: 'BATTALGAZİ'},
  {id: 604, city_id: 44, title: 'DARENDE'},
  {id: 605, city_id: 44, title: 'DOĞANŞEHİR'},
  {id: 606, city_id: 44, title: 'DOĞANYOL'},
  {id: 607, city_id: 44, title: 'HEKİMHAN'},
  {id: 608, city_id: 44, title: 'KALE'},
  {id: 609, city_id: 44, title: 'KULUNCAK'},
  {id: 610, city_id: 44, title: 'MALATYA'},
  {id: 611, city_id: 44, title: 'PÜTÜRGE'},
  {id: 612, city_id: 44, title: 'YAZIHAN'},
  {id: 613, city_id: 44, title: 'YEŞİLYURT'},
  {id: 614, city_id: 45, title: 'AHMETLİ'},
  {id: 615, city_id: 45, title: 'AKHİSAR'},
  {id: 616, city_id: 45, title: 'ALAŞEHİR'},
  {id: 617, city_id: 45, title: 'DEMİRCİ'},
  {id: 618, city_id: 45, title: 'GÖLMARMARA'},
  {id: 619, city_id: 45, title: 'GÖRDES'},
  {id: 620, city_id: 45, title: 'KIRKAĞAÇ'},
  {id: 621, city_id: 45, title: 'KÖPRÜBAŞI'},
  {id: 622, city_id: 45, title: 'KULA'},
  {id: 623, city_id: 45, title: 'MANİSA'},
  {id: 624, city_id: 45, title: 'SALİHLİ'},
  {id: 625, city_id: 45, title: 'SARIGÖL'},
  {id: 626, city_id: 45, title: 'SARUHANLI'},
  {id: 627, city_id: 45, title: 'SELENDİ'},
  {id: 628, city_id: 45, title: 'SOMA'},
  {id: 629, city_id: 45, title: 'TURGUTLU'},
  {id: 630, city_id: 46, title: 'AFŞİN'},
  {id: 631, city_id: 46, title: 'ANDIRIN'},
  {id: 632, city_id: 46, title: 'ÇAĞLIYANCERİT'},
  {id: 633, city_id: 46, title: 'EKİNÖZÜ'},
  {id: 634, city_id: 46, title: 'ELBİSTAN'},
  {id: 635, city_id: 46, title: 'GÖKSUN'},
  {id: 636, city_id: 46, title: 'KAHRAMANMARAŞ'},
  {id: 637, city_id: 46, title: 'NURHAK'},
  {id: 638, city_id: 46, title: 'PAZARCIK'},
  {id: 639, city_id: 46, title: 'TÜRKOĞLU'},
  {id: 640, city_id: 47, title: 'DARGEÇİT'},
  {id: 641, city_id: 47, title: 'DERİK'},
  {id: 642, city_id: 47, title: 'KIZILTEPE'},
  {id: 643, city_id: 47, title: 'MARDİN'},
  {id: 644, city_id: 47, title: 'MAZIDAĞI'},
  {id: 645, city_id: 47, title: 'MİDYAT'},
  {id: 646, city_id: 47, title: 'NUSAYBİN'},
  {id: 647, city_id: 47, title: 'ÖMERLİ'},
  {id: 648, city_id: 47, title: 'SAVUR'},
  {id: 649, city_id: 47, title: 'YEŞİLLİ'},
  {id: 650, city_id: 48, title: 'BODRUM'},
  {id: 651, city_id: 48, title: 'DALAMAN'},
  {id: 652, city_id: 48, title: 'DATÇA'},
  {id: 653, city_id: 48, title: 'FETHİYE'},
  {id: 654, city_id: 48, title: 'KAVAKLIDERE'},
  {id: 655, city_id: 48, title: 'KÖYCEĞİZ'},
  {id: 656, city_id: 48, title: 'MARMARİS'},
  {id: 657, city_id: 48, title: 'MİLAS'},
  {id: 658, city_id: 48, title: 'MUĞLA'},
  {id: 659, city_id: 48, title: 'ORTACA'},
  {id: 660, city_id: 48, title: 'ULA'},
  {id: 661, city_id: 48, title: 'YATAĞAN'},
  {id: 662, city_id: 49, title: 'BULANIK'},
  {id: 663, city_id: 49, title: 'HASKÖY'},
  {id: 664, city_id: 49, title: 'KORKUT'},
  {id: 665, city_id: 49, title: 'MALAZGİRT'},
  {id: 666, city_id: 49, title: 'MUŞ'},
  {id: 667, city_id: 49, title: 'VARTO'},
  {id: 668, city_id: 50, title: 'ACIGÖL'},
  {id: 669, city_id: 50, title: 'AVANOS'},
  {id: 670, city_id: 50, title: 'DERİNKUYU'},
  {id: 671, city_id: 50, title: 'GÜLŞEHİR'},
  {id: 672, city_id: 50, title: 'HACIBEKTAŞ'},
  {id: 673, city_id: 50, title: 'KOZAKLI'},
  {id: 674, city_id: 50, title: 'NEVŞEHİR'},
  {id: 675, city_id: 50, title: 'ÜRGÜP'},
  {id: 676, city_id: 51, title: 'ALTUNHİSAR'},
  {id: 677, city_id: 51, title: 'BOR'},
  {id: 678, city_id: 51, title: 'ÇAMARDI'},
  {id: 679, city_id: 51, title: 'ÇİFTLİK'},
  {id: 680, city_id: 51, title: 'NİĞDE'},
  {id: 681, city_id: 51, title: 'ULUKIŞLA'},
  {id: 682, city_id: 52, title: 'AKKUŞ'},
  {id: 683, city_id: 52, title: 'AYBASTI'},
  {id: 684, city_id: 52, title: 'ÇAMAŞ'},
  {id: 685, city_id: 52, title: 'ÇATALPINAR'},
  {id: 686, city_id: 52, title: 'ÇAYBAŞI'},
  {id: 687, city_id: 52, title: 'FATSA'},
  {id: 688, city_id: 52, title: 'GÖLKÖY'},
  {id: 689, city_id: 52, title: 'GÜLYALI'},
  {id: 690, city_id: 52, title: 'GÜRGENTEPE'},
  {id: 691, city_id: 52, title: 'İKİZCE'},
  {id: 692, city_id: 52, title: 'KABADÜZ'},
  {id: 693, city_id: 52, title: 'KABATAŞ'},
  {id: 694, city_id: 52, title: 'KORGAN'},
  {id: 695, city_id: 52, title: 'KUMRU'},
  {id: 696, city_id: 52, title: 'MESUDİYE'},
  {id: 697, city_id: 52, title: 'ORDU'},
  {id: 698, city_id: 52, title: 'PERŞEMBE'},
  {id: 699, city_id: 52, title: 'ULUBEY'},
  {id: 700, city_id: 52, title: 'ÜNYE'},
  {id: 701, city_id: 53, title: 'ARDEŞEN'},
  {id: 702, city_id: 53, title: 'ÇAMLIHEMŞİN'},
  {id: 703, city_id: 53, title: 'ÇAYELİ'},
  {id: 704, city_id: 53, title: 'DEREPAZARI'},
  {id: 705, city_id: 53, title: 'FINDIKLI'},
  {id: 706, city_id: 53, title: 'GÜNEYSU'},
  {id: 707, city_id: 53, title: 'HEMŞİN'},
  {id: 708, city_id: 53, title: 'İKİZDERE'},
  {id: 709, city_id: 53, title: 'İYİDERE'},
  {id: 710, city_id: 53, title: 'KALKANDERE'},
  {id: 711, city_id: 53, title: 'PAZAR'},
  {id: 712, city_id: 53, title: 'RİZE'},
  {id: 713, city_id: 54, title: 'ADAPAZARI'},
  {id: 714, city_id: 54, title: 'AKYAZI'},
  {id: 715, city_id: 54, title: 'ARİFİYE'},
  {id: 716, city_id: 54, title: 'ERENLER'},
  {id: 717, city_id: 54, title: 'FERİZLİ'},
  {id: 718, city_id: 54, title: 'GEYVE'},
  {id: 719, city_id: 54, title: 'HENDEK'},
  {id: 720, city_id: 54, title: 'KARAPÜRÇEK'},
  {id: 721, city_id: 54, title: 'KARASU'},
  {id: 722, city_id: 54, title: 'KAYNARCA'},
  {id: 723, city_id: 54, title: 'KOCAALİ'},
  {id: 724, city_id: 54, title: 'PAMUKOVA'},
  {id: 725, city_id: 54, title: 'SAPANCA'},
  {id: 726, city_id: 54, title: 'SERDİVAN'},
  {id: 727, city_id: 54, title: 'SÖĞÜTLÜ'},
  {id: 728, city_id: 54, title: 'TARAKLI'},
  {id: 729, city_id: 55, title: 'ALAÇAM'},
  {id: 730, city_id: 55, title: 'ASARCIK'},
  {id: 731, city_id: 55, title: 'ATAKUM'},
  {id: 732, city_id: 55, title: 'AYVACIK'},
  {id: 733, city_id: 55, title: 'BAFRA'},
  {id: 734, city_id: 55, title: 'CANİK'},
  {id: 735, city_id: 55, title: 'ÇARŞAMBA'},
  {id: 736, city_id: 55, title: 'HAVZA'},
  {id: 737, city_id: 55, title: 'İLKADIM'},
  {id: 738, city_id: 55, title: 'KAVAK'},
  {id: 739, city_id: 55, title: 'LADİK'},
  {id: 740, city_id: 55, title: 'ONDOKUZMAYIS'},
  {id: 741, city_id: 55, title: 'SALIPAZARI'},
  {id: 742, city_id: 55, title: 'TEKKEKÖY'},
  {id: 743, city_id: 55, title: 'TERME'},
  {id: 744, city_id: 55, title: 'VEZİRKÖPRÜ'},
  {id: 745, city_id: 55, title: 'YAKAKENT'},
  {id: 746, city_id: 56, title: 'AYDINLAR'},
  {id: 747, city_id: 56, title: 'BAYKAN'},
  {id: 748, city_id: 56, title: 'ERUH'},
  {id: 749, city_id: 56, title: 'KURTALAN'},
  {id: 750, city_id: 56, title: 'PERVARİ'},
  {id: 751, city_id: 56, title: 'SİİRT'},
  {id: 752, city_id: 56, title: 'ŞİRVAN'},
  {id: 753, city_id: 57, title: 'AYANCIK'},
  {id: 754, city_id: 57, title: 'BOYABAT'},
  {id: 755, city_id: 57, title: 'DİKMEN'},
  {id: 756, city_id: 57, title: 'DURAĞAN'},
  {id: 757, city_id: 57, title: 'ERFELEK'},
  {id: 758, city_id: 57, title: 'GERZE'},
  {id: 759, city_id: 57, title: 'SARAYDÜZÜ'},
  {id: 760, city_id: 57, title: 'SİNOP'},
  {id: 761, city_id: 57, title: 'TÜRKELİ'},
  {id: 762, city_id: 58, title: 'AKINCILAR'},
  {id: 763, city_id: 58, title: 'ALTINYAYLA'},
  {id: 764, city_id: 58, title: 'DİVRİĞİ'},
  {id: 765, city_id: 58, title: 'DOĞANŞAR'},
  {id: 766, city_id: 58, title: 'GEMEREK'},
  {id: 767, city_id: 58, title: 'GÖLOVA'},
  {id: 768, city_id: 58, title: 'GÜRÜN'},
  {id: 769, city_id: 58, title: 'HAFİK'},
  {id: 770, city_id: 58, title: 'İMRANLI'},
  {id: 771, city_id: 58, title: 'KANGAL'},
  {id: 772, city_id: 58, title: 'KOYULHİSAR'},
  {id: 773, city_id: 58, title: 'SİVAS'},
  {id: 774, city_id: 58, title: 'SUŞEHRİ'},
  {id: 775, city_id: 58, title: 'ŞARKIŞLA'},
  {id: 776, city_id: 58, title: 'ULAŞ'},
  {id: 777, city_id: 58, title: 'YILDIZELİ'},
  {id: 778, city_id: 58, title: 'ZARA'},
  {id: 779, city_id: 59, title: 'ÇERKEZKÖY'},
  {id: 780, city_id: 59, title: 'ÇORLU'},
  {id: 781, city_id: 59, title: 'HAYRABOLU'},
  {id: 782, city_id: 59, title: 'MALKARA'},
  {id: 783, city_id: 59, title: 'MARMARAEREĞLİSİ'},
  {id: 784, city_id: 59, title: 'MURATLI'},
  {id: 785, city_id: 59, title: 'SARAY'},
  {id: 786, city_id: 59, title: 'ŞARKÖY'},
  {id: 787, city_id: 59, title: 'TEKİRDAĞ'},
  {id: 788, city_id: 60, title: 'ALMUS'},
  {id: 789, city_id: 60, title: 'ARTOVA'},
  {id: 790, city_id: 60, title: 'BAŞÇİFTLİK'},
  {id: 791, city_id: 60, title: 'ERBAA'},
  {id: 792, city_id: 60, title: 'NİKSAR'},
  {id: 793, city_id: 60, title: 'PAZAR'},
  {id: 794, city_id: 60, title: 'REŞADİYE'},
  {id: 795, city_id: 60, title: 'SULUSARAY'},
  {id: 796, city_id: 60, title: 'TOKAT'},
  {id: 797, city_id: 60, title: 'TURHAL'},
  {id: 798, city_id: 60, title: 'YEŞİLYURT'},
  {id: 799, city_id: 60, title: 'ZİLE'},
  {id: 800, city_id: 61, title: 'AKÇAABAT'},
  {id: 801, city_id: 61, title: 'ARAKLI'},
  {id: 802, city_id: 61, title: 'ARSİN'},
  {id: 803, city_id: 61, title: 'BEŞİKDÜZÜ'},
  {id: 804, city_id: 61, title: 'ÇARŞIBAŞI'},
  {id: 805, city_id: 61, title: 'ÇAYKARA'},
  {id: 806, city_id: 61, title: 'DERNEKPAZARI'},
  {id: 807, city_id: 61, title: 'DÜZKÖY'},
  {id: 808, city_id: 61, title: 'HAYRAT'},
  {id: 809, city_id: 61, title: 'KÖPRÜBAŞI'},
  {id: 810, city_id: 61, title: 'MAÇKA'},
  {id: 811, city_id: 61, title: 'OF'},
  {id: 812, city_id: 61, title: 'SÜRMENE'},
  {id: 813, city_id: 61, title: 'ŞALPAZARI'},
  {id: 814, city_id: 61, title: 'TONYA'},
  {id: 815, city_id: 61, title: 'TRABZON'},
  {id: 816, city_id: 61, title: 'VAKFIKEBİR'},
  {id: 817, city_id: 61, title: 'YOMRA'},
  {id: 818, city_id: 62, title: 'ÇEMİŞGEZEK'},
  {id: 819, city_id: 62, title: 'HOZAT'},
  {id: 820, city_id: 62, title: 'MAZGİRT'},
  {id: 821, city_id: 62, title: 'NAZIMİYE'},
  {id: 822, city_id: 62, title: 'OVACIK'},
  {id: 823, city_id: 62, title: 'PERTEK'},
  {id: 824, city_id: 62, title: 'PÜLÜMÜR'},
  {id: 825, city_id: 62, title: 'TUNCELİ'},
  {id: 826, city_id: 63, title: 'AKÇAKALE'},
  {id: 827, city_id: 63, title: 'BİRECİK'},
  {id: 828, city_id: 63, title: 'BOZOVA'},
  {id: 829, city_id: 63, title: 'CEYLANPINAR'},
  {id: 830, city_id: 63, title: 'HALFETİ'},
  {id: 831, city_id: 63, title: 'HARRAN'},
  {id: 832, city_id: 63, title: 'HİLVAN'},
  {id: 833, city_id: 63, title: 'SİVEREK'},
  {id: 834, city_id: 63, title: 'SURUÇ'},
  {id: 835, city_id: 63, title: 'ŞANLIURFA'},
  {id: 836, city_id: 63, title: 'VİRANŞEHİR'},
  {id: 837, city_id: 64, title: 'BANAZ'},
  {id: 838, city_id: 64, title: 'EŞME'},
  {id: 839, city_id: 64, title: 'KARAHALLI'},
  {id: 840, city_id: 64, title: 'SİVASLI'},
  {id: 841, city_id: 64, title: 'ULUBEY'},
  {id: 842, city_id: 64, title: 'UŞAK'},
  {id: 843, city_id: 65, title: 'BAHÇESARAY'},
  {id: 844, city_id: 65, title: 'BAŞKALE'},
  {id: 845, city_id: 65, title: 'ÇALDIRAN'},
  {id: 846, city_id: 65, title: 'ÇATAK'},
  {id: 847, city_id: 65, title: 'EDREMİT'},
  {id: 848, city_id: 65, title: 'ERCİŞ'},
  {id: 849, city_id: 65, title: 'GEVAŞ'},
  {id: 850, city_id: 65, title: 'GÜRPINAR'},
  {id: 851, city_id: 65, title: 'MURADİYE'},
  {id: 852, city_id: 65, title: 'ÖZALP'},
  {id: 853, city_id: 65, title: 'SARAY'},
  {id: 854, city_id: 65, title: 'VAN'},
  {id: 855, city_id: 66, title: 'AKDAĞMADENİ'},
  {id: 856, city_id: 66, title: 'AYDINCIK'},
  {id: 857, city_id: 66, title: 'BOĞAZLIYAN'},
  {id: 858, city_id: 66, title: 'ÇANDIR'},
  {id: 859, city_id: 66, title: 'ÇAYIRALAN'},
  {id: 860, city_id: 66, title: 'ÇEKEREK'},
  {id: 861, city_id: 66, title: 'KADIŞEHRİ'},
  {id: 862, city_id: 66, title: 'SARAYKENT'},
  {id: 863, city_id: 66, title: 'SARIKAYA'},
  {id: 864, city_id: 66, title: 'SORGUN'},
  {id: 865, city_id: 66, title: 'ŞEFAATLİ'},
  {id: 866, city_id: 66, title: 'YENİFAKILI'},
  {id: 867, city_id: 66, title: 'YERKÖY'},
  {id: 868, city_id: 66, title: 'YOZGAT'},
  {id: 869, city_id: 67, title: 'ALAPLI'},
  {id: 870, city_id: 67, title: 'ÇAYCUMA'},
  {id: 871, city_id: 67, title: 'DEVREK'},
  {id: 872, city_id: 67, title: 'GÖKÇEBEY'},
  {id: 873, city_id: 67, title: 'KARADENİZEREĞLİ'},
  {id: 874, city_id: 67, title: 'ZONGULDAK'},
  {id: 875, city_id: 68, title: 'AĞAÇÖREN'},
  {id: 876, city_id: 68, title: 'AKSARAY'},
  {id: 877, city_id: 68, title: 'ESKİL'},
  {id: 878, city_id: 68, title: 'GÜLAĞAÇ'},
  {id: 879, city_id: 68, title: 'GÜZELYURT'},
  {id: 880, city_id: 68, title: 'ORTAKÖY'},
  {id: 881, city_id: 68, title: 'SARIYAHŞİ'},
  {id: 882, city_id: 69, title: 'AYDINTEPE'},
  {id: 883, city_id: 69, title: 'BAYBURT'},
  {id: 884, city_id: 69, title: 'DEMİRÖZÜ'},
  {id: 885, city_id: 70, title: 'AYRANCI'},
  {id: 886, city_id: 70, title: 'BAŞYAYLA'},
  {id: 887, city_id: 70, title: 'ERMENEK'},
  {id: 888, city_id: 70, title: 'KARAMAN'},
  {id: 889, city_id: 70, title: 'KAZIMKARABEKİR'},
  {id: 890, city_id: 70, title: 'SARIVELİLER'},
  {id: 891, city_id: 71, title: 'BAHŞİLİ'},
  {id: 892, city_id: 71, title: 'BALIŞEYH'},
  {id: 893, city_id: 71, title: 'ÇELEBİ'},
  {id: 894, city_id: 71, title: 'DELİCE'},
  {id: 895, city_id: 71, title: 'KARAKEÇİLİ'},
  {id: 896, city_id: 71, title: 'KESKİN'},
  {id: 897, city_id: 71, title: 'KIRIKKALE'},
  {id: 898, city_id: 71, title: 'SULAKYURT'},
  {id: 899, city_id: 71, title: 'YAHŞİHAN'},
  {id: 900, city_id: 72, title: 'BATMAN'},
  {id: 901, city_id: 72, title: 'BEŞİRİ'},
  {id: 902, city_id: 72, title: 'GERCÜŞ'},
  {id: 903, city_id: 72, title: 'HASANKEYF'},
  {id: 904, city_id: 72, title: 'KOZLUK'},
  {id: 905, city_id: 72, title: 'SASON'},
  {id: 906, city_id: 73, title: 'BEYTÜŞŞEBAP'},
  {id: 907, city_id: 73, title: 'CİZRE'},
  {id: 908, city_id: 73, title: 'GÜÇLÜKONAK'},
  {id: 909, city_id: 73, title: 'İDİL'},
  {id: 910, city_id: 73, title: 'SİLOPİ'},
  {id: 911, city_id: 73, title: 'ŞIRNAK'},
  {id: 912, city_id: 73, title: 'ULUDERE'},
  {id: 913, city_id: 74, title: 'AMASRA'},
  {id: 914, city_id: 74, title: 'BARTIN'},
  {id: 915, city_id: 74, title: 'KURUCAŞİLE'},
  {id: 916, city_id: 74, title: 'ULUS'},
  {id: 917, city_id: 75, title: 'ARDAHAN'},
  {id: 918, city_id: 75, title: 'ÇILDIR'},
  {id: 919, city_id: 75, title: 'DAMAL'},
  {id: 920, city_id: 75, title: 'GÖLE'},
  {id: 921, city_id: 75, title: 'HANAK'},
  {id: 922, city_id: 75, title: 'POSOF'},
  {id: 923, city_id: 76, title: 'ARALIK'},
  {id: 924, city_id: 76, title: 'IĞDIR'},
  {id: 925, city_id: 76, title: 'KARAKOYUNLU'},
  {id: 926, city_id: 76, title: 'TUZLUCA'},
  {id: 927, city_id: 77, title: 'ALTINOVA'},
  {id: 928, city_id: 77, title: 'ARMUTLU'},
  {id: 929, city_id: 77, title: 'ÇINARCIK'},
  {id: 930, city_id: 77, title: 'ÇİFTLİKKÖY'},
  {id: 931, city_id: 77, title: 'TERMAL'},
  {id: 932, city_id: 77, title: 'YALOVA'},
  {id: 933, city_id: 78, title: 'EFLANİ'},
  {id: 934, city_id: 78, title: 'ESKİPAZAR'},
  {id: 935, city_id: 78, title: 'KARABÜK'},
  {id: 936, city_id: 78, title: 'OVACIK'},
  {id: 937, city_id: 78, title: 'SAFRANBOLU'},
  {id: 938, city_id: 78, title: 'YENİCE'},
  {id: 939, city_id: 79, title: 'ELBEYLİ'},
  {id: 940, city_id: 79, title: 'KİLİS'},
  {id: 941, city_id: 79, title: 'MUSABEYLİ'},
  {id: 942, city_id: 79, title: 'POLATELİ'},
  {id: 943, city_id: 80, title: 'BAHÇE'},
  {id: 944, city_id: 80, title: 'DÜZİÇİ'},
  {id: 945, city_id: 80, title: 'HASANBEYLİ'},
  {id: 946, city_id: 80, title: 'KADİRLİ'},
  {id: 947, city_id: 80, title: 'OSMANİYE'},
  {id: 948, city_id: 80, title: 'SUMBAS'},
  {id: 949, city_id: 80, title: 'TOPRAKKALE'},
  {id: 950, city_id: 81, title: 'AKÇAKOCA'},
  {id: 951, city_id: 81, title: 'CUMAYERİ'},
  {id: 952, city_id: 81, title: 'ÇİLİMLİ'},
  {id: 953, city_id: 81, title: 'DÜZCE'},
  {id: 954, city_id: 81, title: 'GÖLYAKA'},
  {id: 955, city_id: 81, title: 'GÜMÜŞOVA'},
  {id: 956, city_id: 81, title: 'KAYNAŞLI'},
  {id: 957, city_id: 81, title: 'YIĞILCA'},
  // Add all other counties here
];

const CityCountySelector = ({ residence = { city_id: "", county_id: "", address: "" }, setFormData }) => {
    const [selectedCity, setSelectedCity] = useState("");
    const [selectedCounty, setSelectedCounty] = useState("");
    const [address, setAddress] = useState("");
  
    // Filter counties based on selected city
    const filteredCounties = counties.filter(
      (county) => county.city_id === parseInt(selectedCity)
    );
  
    const handleCityChange = (e) => {
      const cityValue = e.target.value;
      setSelectedCity(cityValue);
      setSelectedCounty(""); // Reset county selection when city changes
  
      // Update formData with selected city and reset county
      console.log(cityValue)
      setFormData((prev) => ({
        ...prev,
        residence: {
          ...prev.residence,
          city_id: cityValue,
          county_id: "", // Reset county when city changes
        },
      }));
    };
  
    const handleCountyChange = (e) => {
      const countyValue = e.target.value;
      setSelectedCounty(countyValue);
  
      // Update formData with selected county
      console.log(countyValue)
      setFormData((prev) => ({
        ...prev,
        residence: {
          ...prev.residence,
          county_id: countyValue,
        },
      }));
    };
  
    const handleAddressChange = (e) => {
      const addressValue = e.target.value;
      setAddress(addressValue);
      
      // Update formData with the new address within the residence object
      setFormData((prev) => ({
        ...prev,
        residence: {
          ...prev.residence,
          address: addressValue,
        },
      }));
    };
  
    return (
      <div className="city-county-selector">
        <div className="form-group">
          <label htmlFor="city" className="block text-sm font-medium text-gray-700">
            City
          </label>
          <select
            id="city"
            name="city"
            value={selectedCity}
            onChange={handleCityChange}
            className="w-full px-4 py-2 rounded-md border border-input focus:outline-none focus:ring-2 focus:ring-ring bg-background"
          >
            <option value="">Select a city</option>
            {cities.map((city) => (
              <option key={city.id} value={city.id}>
                {city.title}
              </option>
            ))}
          </select>
        </div>
  
        <div className="form-group mt-4">
          <label htmlFor="county" className="block text-sm font-medium text-gray-700">
            County
          </label>
          <select
            id="county"
            name="county"
            value={selectedCounty}
            onChange={handleCountyChange}
            className="w-full px-4 py-2 rounded-md border border-input focus:outline-none focus:ring-2 focus:ring-ring bg-background"
            disabled={!selectedCity} // Disable until a city is selected
          >
            <option value="">Select a county</option>
            {filteredCounties.map((county) => (
              <option key={county.id} value={county.id}>
                {county.title}
              </option>
            ))}
          </select>
        </div>
  
        <div className="md:col-span-2 mt-6">
          <label htmlFor="address" className="text-white block text-body font-body text-foreground mb-2">
            Address
          </label>
          <textarea
            id="address"
            name="address"
            required
            value={address}
            onChange={handleAddressChange}
            rows="3"
            className="w-full px-4 py-2 rounded-md border border-input focus:outline-none focus:ring-2 focus:ring-ring bg-background"
          ></textarea>
        </div>
  
        <div className="mt-6">
          <p>Selected City: {cities.find((city) => city.id === parseInt(selectedCity))?.title || "None"}</p>
          <p>Selected County: {counties.find((county) => county.id === parseInt(selectedCounty))?.title || "None"}</p>
        </div>
      </div>
    );
};
  

export default CityCountySelector;
